# Establece la imagen base
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo requirements.txt
COPY assesment_factored_back/requirements.txt .

# Instala las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto de los archivos de la aplicación
COPY assesment_factored_back/ .

# Expone el puerto en el que la aplicación estará corriendo
EXPOSE 5000

# Comando para correr la aplicación
CMD ["sh", "-c", "./wait-for-it.sh db:3306 -- python app.py"]
