version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/apiDB
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  db_init:
    image: mysql:8.0
    depends_on:
      - db
      - backend
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiDB
    entrypoint: [ "sh", "-c", "/wait-for-it.sh backend:5000 -- /wait-for-it.sh db:3306 -- mysql -h db -u root -proot apiDB < /docker-entrypoint-initdb.d/init.sql" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
